# This is Foreman's configuration file. You can edit it to tell Foreman about
# new tools that you'd like to install, or to change versions of tools you
# already have.

# When adding new tools, make sure to run `foreman install` so that their
# binaries are installed.

[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.0.0-rc.3" }
remodel = { source = "rojo-rbx/remodel", version = "0.9.1" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.11.1" }
wally = { source = "UpliftGames/wally", version = "0.3.0" }
tarmac = { source = "Roblox/tarmac", version = "0.7.0" }
selene = { source = "Kampfkarren/selene", version = "0.15.0" }

