# ~/.config/starship.toml

# Use custom format
format = """
$username\b\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_state\
$line_break\
$character
"""

[username]
format = "[$user]($style) "
style_user = "fg:#12a0ff"
show_always = true

[hostname]
format = "[@$hostname]($style) "
style = "fg:#12a0ff"
ssh_only = false

[directory]
truncation_length = 2
truncate_to_repo = false
truncation_symbol = "../"
style = "fg:#5f636e"

[character]
success_symbol = "[λ](white)"
error_symbol = "[λ](white)"

[git_branch]
format = "[\\($branch\\)]($style) "
style = "purple"
only_attached = true

[git_commit]
format = "[\\($hash$tag\\)]($style) "
style = "purple"
tag_disabled = false
only_detached = true

[git_status]
style = "red"
